M48
; DRILL file {KiCad 7.0.1} date Mon Mar 13 20:18:59 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-13T20:18:59+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0787
%
G90
G05
T1
X4.4706Y-5.372
X4.4706Y-5.5629
T2
X4.5898Y-5.3602
X4.5898Y-5.5747
T3
X3.3898Y-6.378
X3.7362Y-6.378
T0
M30
